nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./app
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./app
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./app
    links:
        - redis
    ports:
        - "8080"
redis:
    build: ./redis
    ports:
        - "6379"
